FROM nvidia/cuda:12.2.0-devel-ubuntu22.04

# 安裝 Python、pip、指定 Nsight Compute 版本（這裡用 2024.1.0）
RUN apt update && apt install -y \
    python3 python3-pip wget unzip \
    nsight-compute-2024.1.0 \
 && pip3 install torch torchvision ultralytics opencv-python

# 拷貝測試腳本與圖片

WORKDIR /app

ENTRYPOINT ["bash"]
