apiVersion: v1
kind: Pod
metadata:
  name: pose-3-30563
  labels:
    app: 
spec:
  nodeSelector:
      gpuNode: lab
  containers:
  - name: pose
    image:  hiro08081/pose:1
    readinessProbe:
      tcpSocket:
        port: 50052
      initialDelaySeconds: 5
      periodSeconds: 5
    ports:
    - containerPort: 50052
      hostPort: 30563
    resources:
      limits:
        nvidia.com/gpu: 1